name = "3eal"
main = "worker/index.ts"
compatibility_date = "2026-10-09"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[vars]
TURNSTILE_SITE_KEY = ""
WEB_ANALYTICS_TOKEN = ""

[observability]
enabled = true
